chore: add group info page
savannahghi/afyamoja pull request #194
Opened 2022-03-08 10:34 UTC by byronkimani

- add group info page
![Screenshot_1646735433](https://user-images.githubusercontent.com/40171348/157219320-a5cb2121-c978-4540-8d21-a041a64dea85.png)

Signed-off-by: Byron Kimani <byronkimani@gmail.com>

2022-03-08 15:38 UTC, abiudrn requested changes

2022-03-08 15:38 UTC, abiudrn commented on lib/application/core/services/utils.dart
> +const List<Widget> membersList = <Widget>[
There is an API to list group members...

2022-03-08 15:38 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +const String changePermissionsText = 'Change permissions';
This was to be removed. Let's have these options for now.
![Group 692](https://user-images.githubusercontent.com/23169205/157271018-780e39d0-5746-4514-a3a7-ec1d0e61200d.png)

2022-03-08 15:38 UTC, abiudrn commented on lib/presentation/community/group_info/pages/group_info_page.dart
> +                    style: const TextStyle(
use the already defined TextThemes for example `boldSize16Text(AppColors.greyTextColor)`

2022-03-09 09:33 UTC, EugeneDevv approved these changes

2022-03-09 09:44 UTC, abiudrn approved these changes

2022-03-09 09:54 UTC, merged