chore: create group fixes
savannahghi/afyamoja pull request #240
Opened 2022-03-19 10:06 UTC by johnngugi

2022-03-19 10:15 UTC, abiudrn requested changes

2022-03-19 10:15 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +const String groupNameHintText = 'Name of the group...';
Change this to `Name your new group...`. Also, grey out the text a bit like so 
![Group 749](https://user-images.githubusercontent.com/23169205/159117030-083bddb8-76e0-4738-8678-8451636a5528.png)

2022-03-19 10:15 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +const String groupDescriptionHintText = 'Description of the group...';
Change this to `Describe your new group...`

2022-03-19 13:14 UTC, abiudrn approved these changes

2022-03-21 06:07 UTC, abiudrn approved these changes

2022-03-21 06:09 UTC, Paulmburu approved these changes

2022-03-21 06:10 UTC, merged