feat: unban community member
savannahghi/afyamoja pull request #271
Opened 2022-03-24 07:47 UTC by EugeneDevv

2022-03-25 15:48 UTC, abiudrn approved these changes

2022-03-26 06:06 UTC, byronkimani approved these changes

2022-03-26 08:00 UTC, abiudrn requested changes

2022-03-26 08:00 UTC, abiudrn commented on test/widget_tests/presentation/community/member_list_actions_dialog_test.dart
> +      expect(find.byType(SnackBar, skipOffstage: false), findsOneWidget);
Verify the contents of the snackbar for all these tests

2022-03-26 18:08 UTC, Paulmburu approved these changes

2022-03-28 12:10 UTC, johnngugi approved these changes

2022-03-28 12:17 UTC, abiudrn approved these changes

2022-03-28 12:17 UTC, merged