feat: invited communities
savannahghi/afyamoja pull request #274
Opened 2022-03-24 13:55 UTC by Paulmburu

2022-03-24 18:53 UTC, abiudrn approved these changes

2022-03-24 18:53 UTC, abiudrn commented on lib/application/redux/actions/communities/accept_decline_communities_invite_action.dart
> +class AcceptDeclineCommunitiesInviteAction extends ReduxAction<AppState> {
Split this action into two that do one thing and one thing only. 

1. `AcceptCommunituInviteAction`
2. `RejectCommunituInviteAction`

2022-03-24 18:53 UTC, abiudrn commented on lib/application/redux/actions/communities/accept_decline_communities_invite_action.dart
> +      onSuccess?.call(InvitationAction.REJECT);
This conditional indexing is why the comment above needs to be handled. Debugging this will be difficult.

2022-03-24 18:53 UTC, abiudrn commented on test/widget_tests/presentation/community/invited_groups/pages/accept_group_invites_page_test.dart
> +        // ..staffState!.copyWith(facilityID: 'id'),
Remove dead code here

2022-03-24 18:53 UTC, abiudrn commented on test/widget_tests/presentation/community/invited_groups/pages/accept_group_invites_page_test.dart
> +      expect(find.byType(SnackBar), findsOneWidget);
Verify the contents of the Snackbar i.e the error message

2022-03-25 13:17 UTC, johnngugi approved these changes

2022-03-25 14:18 UTC, abiudrn requested changes

2022-03-25 14:18 UTC, abiudrn commented on lib/application/redux/actions/communities/accept_communities_invite_action.dart
> +      onSuccess?.call(InvitationAction.UNKNOWN);
should it call `onSuccess()` or `onError()`

2022-03-25 14:18 UTC, abiudrn commented on lib/application/redux/actions/communities/decline_communities_invite_action.dart
> +      onSuccess?.call(InvitationAction.UNKNOWN);
shouldn't this call `onFailure()`

2022-03-26 08:56 UTC, abiudrn approved these changes

2022-03-26 08:56 UTC, merged