fix: record security questions
savannahghi/afyamoja pull request #357
Opened 2022-04-29 09:47 UTC by Paulmburu

2022-04-29 11:29 UTC, abiudrn requested changes

2022-04-29 11:29 UTC, abiudrn commented on lib/main.dart
> +  return initApp(demoAppContexts);
Revert this

2022-05-05 06:47 UTC, johnngugi approved these changes

2022-05-05 06:58 UTC, abiudrn approved these changes

2022-05-05 06:58 UTC, merged