refactor: bottom nav indexing
savannahghi/afyamoja pull request #368
Opened 2022-05-06 07:01 UTC by Paulmburu

2022-05-07 10:01 UTC, abiudrn requested changes

2022-05-07 10:01 UTC, abiudrn commented on lib/presentation/engagement/home/pages/home_page.dart
> +        bottomNavIndex: 0,
Replace this with the enum index to ensure consistency in case it changes positions in future.

More information [here](https://api.dart.dev/stable/2.16.1/dart-core/Enum/index.html)

```suggestion
        bottomNavIndex: BottomNavIndex.home.index,
```

2022-05-07 10:01 UTC, abiudrn commented on lib/presentation/notifications/notifications_page.dart
> +        bottomNavIndex: 2,
Use the enum index. refere to comment above

2022-05-10 06:03 UTC, byronkimani approved these changes

2022-05-11 07:27 UTC, abiudrn approved these changes

2022-05-11 07:28 UTC, johnngugi approved these changes

2022-05-11 08:48 UTC, merged